# Generated by Django 5.0 on 2023-12-18 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0001_initial'),
        ('localizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('identificacion', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=500)),
                ('apellidos', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=False)),
                ('cargo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargos.cargos')),
                ('localizacion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='localizaciones.localizaciones')),
            ],
        ),
    ]
